<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $productRepo = app(\App\Repositories\Interfaces\ProductRepositoryInterface::class);

        $tours = [
            // Tour Trong Nuoc (category_id = 1)
            [
                'name_vn' => 'Tour Du Lịch Hạ Long 2 Ngày 1 Đêm Du Thuyền 5 Sao',
                'name_en' => 'Ha Long Bay 2 Days 1 Night 5-Star Cruise Tour',
                'intro_vn' => 'Trải nghiệm du thuyền đẳng cấp 5 sao tại vịnh Hạ Long kỳ vĩ với lịch trình hấp dẫn.',
                'intro_en' => 'Experience a premium 5-star cruise in majestic Ha Long Bay with an exciting itinerary.',
                'price' => 3450000,
                'price_old' => 4500000,
                'content_vn' => '<p>Khám phá vịnh Hạ Long - kỳ quan thiên nhiên thế giới trên du thuyền sang trọng. Bao gồm trọn gói dịch vụ ăn uống, chèo thuyền kayak, tham quan hang động lung linh.</p>',
                'content_en' => '<p>Discover Ha Long Bay - a world natural wonder on a luxury cruise. Includes all-inclusive dining, kayaking, and cave exploration.</p>',
                'image_vn' => 'tour_6.jpg',
                'image_en' => 'tour_6.jpg',
                'category_id' => 1,
                'hot' => true,
            ],
            [
                'name_vn' => 'Tour Hà Giang Hùng Vĩ Cột Cờ Lũng Cú 3 Ngày 2 Đêm',
                'name_en' => 'Ha Giang Loop & Lung Cu Flag Tower 3 Days 2 Nights',
                'intro_vn' => 'Chinh phục Mã Pí Lèng, sông Nho Quế và check-in Cột cờ cực Bắc Tổ Quốc.',
                'intro_en' => 'Conquer Ma Pi Leng pass, Nho Que river and check-in the northernmost Flag Tower.',
                'price' => 2890000,
                'price_old' => 3500000,
                'content_vn' => '<p>Hành trình khám phá cao nguyên đá Đồng Văn hùng vĩ, hoa tam giác mạch khoe sắc và nét văn hóa đặc sắc của đồng bào vùng cao.</p>',
                'content_en' => '<p>A journey to discover the majestic Dong Van karst plateau, blooming buckwheat flowers, and unique ethnic cultures.</p>',
                'image_vn' => 'tour_10.jpg',
                'image_en' => 'tour_10.jpg',
                'category_id' => 1,
                'hot' => true,
            ],
            [
                'name_vn' => 'Tour Đà Nẵng - Hội An - Bà Nà Hills 4 Ngày 3 Đêm',
                'name_en' => 'Da Nang - Hoi An - Ba Na Hills 4 Days 3 Nights',
                'intro_vn' => 'Khám phá Cầu Vàng nổi tiếng, phố cổ Hội An rực rỡ và bãi biển Mỹ Khê tuyệt đẹp.',
                'intro_en' => 'Explore the famous Golden Bridge, colorful Hoi An ancient town and gorgeous My Khe beach.',
                'price' => 4990000,
                'price_old' => 5800000,
                'content_vn' => '<p>Lịch trình trọn gói tham quan Bà Nà Hills, bán đảo Sơn Trà, Ngũ Hành Sơn và dạo quanh phố cổ Hội An về đêm lung linh ánh đèn lồng.</p>',
                'content_en' => '<p>All-inclusive itinerary visiting Ba Na Hills, Son Tra peninsula, Marble Mountains, and strolling through Hoi An ancient town.</p>',
                'image_vn' => 'tour_3.jpg',
                'image_en' => 'tour_3.jpg',
                'category_id' => 1,
                'hot' => false,
            ],
            [
                'name_vn' => 'Tour Phú Quốc Thiên Đường Đảo Ngọc 3 Ngày 2 Đêm',
                'name_en' => 'Phu Quoc Island Paradise 3 Days 2 Nights',
                'intro_vn' => 'Vui chơi tại Grand World, ngắm hoàng hôn tại Sunset Sanato và lặn ngắm san hô.',
                'intro_en' => 'Have fun at Grand World, watch the sunset at Sunset Sanato, and go snorkeling.',
                'price' => 4250000,
                'price_old' => 5000000,
                'content_vn' => '<p>Tận hưởng kỳ nghỉ dưỡng tuyệt vời tại đảo ngọc Phú Quốc với bãi cát trắng mịn, tham quan cơ sở sản xuất ngọc trai, nước mắm truyền thống.</p>',
                'content_en' => '<p>Enjoy a wonderful holiday in Phu Quoc emerald island with white sand beach, visiting pearl farm and traditional fish sauce facility.</p>',
                'image_vn' => 'tour_5.jpg',
                'image_en' => 'tour_5.jpg',
                'category_id' => 1,
                'hot' => false,
            ],

            // Tour Quoc Te (category_id = 2)
            [
                'name_vn' => 'Tour Du Lịch Nhật Bản Mùa Hoa Anh Đào Cung Đường Vàng 6 Ngày 5 Đêm',
                'name_en' => 'Japan Cherry Blossom Golden Route 6 Days 5 Nights',
                'intro_vn' => 'Hành trình Tokyo - Núi Phú Sĩ - Kyoto - Osaka ngắm hoa anh đào rực rỡ.',
                'intro_en' => 'Tokyo - Mt Fuji - Kyoto - Osaka route to watch beautiful cherry blossoms.',
                'price' => 28900000,
                'price_old' => 32000000,
                'content_vn' => '<p>Khám phá văn hóa truyền thống xen lẫn hiện đại của xứ sở Mặt trời mọc. Trải nghiệm tàu Shinkansen tốc độ cao và tắm Onsen truyền thống.</p>',
                'content_en' => '<p>Explore traditional and modern culture of Japan. Experience high-speed Shinkansen train and traditional Onsen hot spring.</p>',
                'image_vn' => 'tour_2.jpg',
                'image_en' => 'tour_2.jpg',
                'category_id' => 2,
                'hot' => true,
            ],
            [
                'name_vn' => 'Tour Pháp - Thụy Sĩ - Ý Hành Trình Châu Âu Cổ Kính 9 Ngày 8 Đêm',
                'name_en' => 'France - Switzerland - Italy Classic Europe 9 Days 8 Nights',
                'intro_vn' => 'Tham quan Tháp Eiffel, Venice thơ mộng và đỉnh núi tuyết Titlis hùng vĩ.',
                'intro_en' => 'Visit Eiffel Tower, romantic Venice, and magnificent Mt Titlis snow peak.',
                'price' => 59900000,
                'price_old' => 65000000,
                'content_vn' => '<p>Cung đường du lịch đẹp nhất châu Âu đi qua các thành phố lịch sử: Paris hoa lệ, Lucerne thanh bình, Milan thời trang, Venice cổ kính và Rome vĩ đại.</p>',
                'content_en' => '<p>Europe\'s most beautiful travel route visiting historical cities: Paris, Lucerne, Milan, Venice, and Rome.</p>',
                'image_vn' => 'tour_8.jpg',
                'image_en' => 'tour_8.jpg',
                'category_id' => 2,
                'hot' => true,
            ],
            [
                'name_vn' => 'Tour Du Lịch Hàn Quốc Mùa Thu Lãng Mạn Seoul - Nami 5 Ngày 4 Đêm',
                'name_en' => 'Korea Romantic Autumn Seoul - Nami 5 Days 4 Nights',
                'intro_vn' => 'Chiêm ngưỡng lá vàng lá đỏ tại đảo Nami, cung điện Gyeongbokgung cổ kính.',
                'intro_en' => 'Admire yellow and red leaves at Nami Island, and ancient Gyeongbokgung Palace.',
                'price' => 12900000,
                'price_old' => 14500000,
                'content_vn' => '<p>Trải nghiệm làm kim chi, mặc áo Hanbok truyền thống, tham quan tháp Namsan tình yêu và mua sắm tại chợ Myeongdong sầm uất.</p>',
                'content_en' => '<p>Experience making kimchi, wearing traditional Hanbok, visiting Namsan Tower, and shopping at Myeongdong market.</p>',
                'image_vn' => 'tour_1.jpg',
                'image_en' => 'tour_1.jpg',
                'category_id' => 2,
                'hot' => false,
            ],
            [
                'name_vn' => 'Tour Du Lịch Thái Lan Bangkok - Pattaya Bay Trọn Gói 5 Ngày 4 Đêm',
                'name_en' => 'Thailand Bangkok - Pattaya All-Inclusive 5 Days 4 Nights',
                'intro_vn' => 'Khám phá Chùa Phật Vàng, đảo San Hô Coral và show diễn Alcazar hoành tráng.',
                'intro_en' => 'Explore Golden Buddha Temple, Coral Island and spectacular Alcazar show.',
                'price' => 6490000,
                'price_old' => 7500000,
                'content_vn' => '<p>Tour du lịch Thái Lan giá tốt nhất, bay hãng hàng không quốc gia, thưởng thức buffet nhà hàng xoay 86 tầng Baiyoke Sky và massage Thái truyền thống.</p>',
                'content_en' => '<p>Thailand tour at the best price, flying national airline, enjoying Baiyoke Sky buffet and traditional Thai massage.</p>',
                'image_vn' => 'tour_4.jpg',
                'image_en' => 'tour_4.jpg',
                'category_id' => 2,
                'hot' => false,
            ],

            // Tour Cao Cap (category_id = 3)
            [
                'name_vn' => 'Tour Nghỉ Dưỡng Siêu Sang Maldives 5 Ngày 4 Đêm Resort 5 Sao Tròn Gói',
                'name_en' => 'Luxury Maldives Resort 5 Days 4 Nights All-Inclusive',
                'intro_vn' => 'Nghỉ dưỡng tại Water Villa trên mặt nước biển xanh ngọc, máy bay thủy phi cơ đưa đón.',
                'intro_en' => 'Stay at Overwater Water Villa, seaplane transfers, and premium meals.',
                'price' => 45000000,
                'price_old' => 49900000,
                'content_vn' => '<p>Trải nghiệm thiên đường hạ giới Maldives với dịch vụ quản gia riêng, các bữa ăn cao cấp và không giới hạn đồ uống uống tại resort.</p>',
                'content_en' => '<p>Experience Maldives paradise with private butler service, premium dining and unlimited resort beverages.</p>',
                'image_vn' => 'tour_7.jpg',
                'image_en' => 'tour_7.jpg',
                'category_id' => 3,
                'hot' => true,
            ],
            [
                'name_vn' => 'Tour Thưởng Ngoạn Mùa Thu Thụy Sĩ - Ngôi Làng Cổ Grindelwald 8 Ngày 7 Đêm',
                'name_en' => 'Switzerland Autumn Grindelwald Scenic Tour 8 Days 7 Nights',
                'intro_vn' => 'Nghỉ dưỡng tại chalets gỗ truyền thống dưới chân núi Eiger, đi xe lửa leo núi răng cưa.',
                'intro_en' => 'Stay in traditional wooden chalets under Mt Eiger, and ride cogwheel alpine train.',
                'price' => 79000000,
                'price_old' => 85000000,
                'content_vn' => '<p>Khám phá vùng núi Jungfrau thơ mộng, thưởng ngoạn hồ Thun và Brienz xanh ngắt bằng du thuyền hạng nhất, trải nghiệm ẩm thực phô mai Thụy Sĩ đỉnh cao.</p>',
                'content_en' => '<p>Discover Jungfrau mountain region, cruise Lake Thun and Brienz in first-class, and experience swiss cheese fondue.</p>',
                'image_vn' => 'tour_9.jpg',
                'image_en' => 'tour_9.jpg',
                'category_id' => 3,
                'hot' => true,
            ],
            [
                'name_vn' => 'Tour Châu Âu Cánh Đồng Hoa Oải Hương Provence - Monaco 8 Ngày 7 Đêm',
                'name_en' => 'Europe Provence Lavender Fields & Monaco 8 Days 7 Nights',
                'intro_vn' => 'Ngắm hoa oải hương tím ngắt miền nam nước Pháp, sòng bài sang trọng tại Monaco.',
                'intro_en' => 'Watch purple lavender fields in Southern France, and luxury casino in Monaco.',
                'price' => 69000000,
                'price_old' => 74000000,
                'content_vn' => '<p>Tour trải nghiệm chuyên sâu vùng Provence cổ kính, nghỉ dưỡng tại khách sạn lâu đài cổ, thưởng thức rượu vang Pháp trứ danh.</p>',
                'content_en' => '<p>In-depth tour of Provence, stay at historic castle hotels, and taste famous French wines.</p>',
                'image_vn' => 'tour_11.jpg',
                'image_en' => 'tour_11.jpg',
                'category_id' => 3,
                'hot' => false,
            ],
            [
                'name_vn' => 'Tour Sa Mạc Dubai Nghỉ Dưỡng Khách Sạn Cánh Buồm 7 Sao Burj Al Arab 5 Ngày 4 Đêm',
                'name_en' => 'Dubai Desert & Burj Al Arab 7-Star Hotel 5 Days 4 Nights',
                'intro_vn' => 'Nghỉ dưỡng siêu sang tại Burj Al Arab, bay trực thăng ngắm đảo cọ Palm Jumeirah.',
                'intro_en' => 'Stay at Burj Al Arab 7-star hotel, and helicopter tour over Palm Jumeirah.',
                'price' => 88000000,
                'price_old' => 95000000,
                'content_vn' => '<p>Tour nghỉ dưỡng đỉnh cao tại Dubai hoàng gia. Đi siêu xe trên sa mạc safari, ăn tối sang trọng tại nhà hàng dưới lòng đại dương.</p>',
                'content_en' => '<p>Ultimate luxury holiday in royal Dubai. Drive supercars on desert safari, and dine at undersea restaurant.</p>',
                'image_vn' => 'tour_12.jpg',
                'image_en' => 'tour_12.jpg',
                'category_id' => 3,
                'hot' => false,
            ],
        ];

        foreach ($tours as $idx => $tourData) {
            $productRepo->createWithAutoSlug([
                'name_vn' => $tourData['name_vn'],
                'name_en' => $tourData['name_en'],
                'intro_vn' => $tourData['intro_vn'],
                'intro_en' => $tourData['intro_en'],
                'price' => $tourData['price'],
                'price_old' => $tourData['price_old'],
                'content_vn' => $tourData['content_vn'],
                'content_en' => $tourData['content_en'],
                'image_vn' => 'uploads/product/' . $tourData['image_vn'],
                'image_en' => 'uploads/product/' . $tourData['image_en'],
                'image_detail' => null,
                'status' => true,
                'hot' => $tourData['hot'],
                'stt' => $idx + 1,
                'keyword_vn' => 'tour, du lich, ' . $tourData['name_vn'],
                'keyword_en' => 'tour, travel, ' . $tourData['name_en'],
                'description_vn' => $tourData['intro_vn'],
                'description_en' => $tourData['intro_en'],
                'category_id' => $tourData['category_id'],
                'uuid' => Str::uuid()->toString(),
            ]);
        }
    }
}
